### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by robsdedude** [PhantomBot/PhantomBot#2321]
PhantomBot Version: 3.2.0-NB-20200618 (nightly_build)
O/S Version: Raspbian 9.8
Java Version: Java 11.0.6 running on Linux 4.14.98-v7+ (arm)

I found this in the error logs and I had to restart my bot to make it work properly again. Sadly I cannot tell you what happend in chat at that time. I hope that the log gives you enough info to reproduce the bug. If not, feel free to just close the issue. robsdebot is the name of the bot btw.

```
[07-14-2020 @ 21:27:20.626 GMT] [parseData()@TwitchWSIRCParser.java:172] Failed to parse Twitch message: [Index 1 out of bounds for length 1] 

 {@badge-info=;badges=moderator/1;color=;display-name=robsdebot;emote-sets=0,300374282,537206155;mod=1;subscriber=0;user-type=mod :tmi.twitch.tv USERSTATE #robsdedude
PONG :tmi.twitch.tv
}

[07-14-2020 @ 21:27:20.679 GMT] java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at tv.phantombot.twitch.irc.TwitchWSIRCParser.parseLine(TwitchWSIRCParser.java:287)
        at tv.phantombot.twitch.irc.TwitchWSIRCParser.parseData(TwitchWSIRCParser.java:166)
        at tv.phantombot.twitch.irc.TwitchWSIRC.lambda$onMessage$1(TwitchWSIRC.java:189)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gmt2001** [comment]
**Trace**
https://github.com/PhantomBot/PhantomBot/blob/6f9f4465400921c21f710545094d6de51f4657ac/source/tv/phantombot/twitch/irc/TwitchWSIRCParser.java#L286-L287

https://github.com/PhantomBot/PhantomBot/blob/6f9f4465400921c21f710545094d6de51f4657ac/source/tv/phantombot/twitch/irc/TwitchWSIRCParser.java#L160-L175

https://github.com/PhantomBot/PhantomBot/blob/6f9f4465400921c21f710545094d6de51f4657ac/source/tv/phantombot/twitch/irc/TwitchWSIRC.java#L181-L196

**State**
```
rawMessage = "PONG :tmi.twitch.tv";
tags = Map<String, String> {};
messageParts = ["PONG", "tmi.twitch.tv"];
username = "";
message = "tmi.twitch.tv";
event = null;
```
