### ISSUE TITLE
Bot doesn't close the SQLite database on shutdown

### ISSUE THREAD

**Issue by Nekroido** [PhantomBot/PhantomBot#2450]
PhantomBot Version: 3.4.1
O/S Version: Windows/Linux/macOS
Java Version: any

Detailed Description:

The application doesn't close the `phantombot.db` file on shutdown effectively locking itself out into read-only mode, which causes an assortment of annoyances like discord alert spam, locked out settings, and lost chat time and points tracking. The application was upgraded from 2.4.1 a few days after Twitch died on everyone on 26th of January.

Steps to Reproduce:

1. Start the application.
2. Type `exit`, press Enter, and wait for the shutdown.
3. The `config` folder will still have the `phantombot.db-shm` and `phantombot.db-wal` files.
4. Start the application again and enjoy the SQLite locked error message spam.

Logs:

I'll trim it to just two messages because the log's size for a single day is 32MB.

```
[02-06-2021 @ 00:00:01.430 GMT] org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:1010)
	at org.sqlite.core.DB.newSQLException(DB.java:1022)
	at org.sqlite.core.DB.execute(DB.java:861)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
	at com.gmt2001.datastore.SqliteStore.SetString(SqliteStore.java:905)
	at tv.phantombot.cache.TwitchCache.setDBString(TwitchCache.java:578)
	at tv.phantombot.cache.TwitchCache.updateClips(TwitchCache.java:201)
	at tv.phantombot.cache.TwitchCache.run(TwitchCache.java:158)
	at java.base/java.lang.Thread.run(Unknown Source)


[02-06-2021 @ 00:00:01.501 GMT] org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:1010)
	at org.sqlite.core.DB.newSQLException(DB.java:1022)
	at org.sqlite.core.DB.execute(DB.java:861)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
	at com.gmt2001.datastore.SqliteStore.SetString(SqliteStore.java:905)
	at com.gmt2001.datastore.DataStore.set(DataStore.java:278)
	at jdk.internal.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:65)
	at org.mozilla.javascript.gen.lastseenCommand_js_104._c_anonymous_2(lastseenCommand.js:28)
	at org.mozilla.javascript.gen.lastseenCommand_js_104.call(lastseenCommand.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:45)
	at org.mozilla.javascript.gen.init_js_1._c_callHook_21(init.js:318)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:76)
	at org.mozilla.javascript.gen.init_js_1._c_anonymous_37(init.js:674)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:559)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy10.handle(Unknown Source)
	at tv.phantombot.script.ScriptEventManager.onEvent(ScriptEventManager.java:75)
	at jdk.internal.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:29)
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:42)
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:72)
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:49)
	at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:67)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Nekroido** [comment]
Looks like the whole datastore package rewrite is riddled with bugs. GetKeyList() returns wrong result set. HasKey() doesn't behave correctly which leads to data overwrites. I regret upgrading to v3. What a mess.
