### ISSUE TITLE
Discord Integration breaks commands

### ISSUE THREAD

**Issue by Sartharon** [PhantomBot/PhantomBot#2456]
PhantomBot Version: 3.4.2 (stable) (Revision: bf69ab8)
O/S Version: Ubuntu 20.04LTS
Java Version: 11.0.9.1+1 (OpenJDK)
Web Browser Version (if Panel related): 

Detailed Description:
Adding `discord_token=<TOKEN>` to botlogin.txt prefents the first start since it gets stuck on `Successfully authenticated with Discord `

Adding discord_token later after the first run lets the bot start correctly but commands are not working anymore see logs (provided below)

Steps to Reproduce:

1. Follow Installation guide and unzip Phantombot.
2. Create a botlogin.txt and already enter your oauth keys and discord token.
3. Start the bot

Logs:

Screenshots (if applicable):
<details>
  <summary><b>Error log:</b></summary>

```
[02-25-2021 @ 15:59:09.370 GMT] [onEvent()@ScriptEventManager.java:79] Failed to dispatch event tv.phantombot.event.command.CommandEvent

[02-25-2021 @ 15:59:09.371 GMT] org.mozilla.javascript.EcmaError: ReferenceError: "bot" is not defined. (init.js#468)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4236)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4214)
	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4304)
	at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1990)
	at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1929)
	at org.mozilla.javascript.gen.init_js_1._c_anonymous_27(init.js:468)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:559)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy16.handle(Unknown Source)
	at tv.phantombot.script.ScriptEventManager.onEvent(ScriptEventManager.java:75)
	at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:29)
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:42)
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:72)
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:49)
	at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:67)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

**Comment by Sartharon** [comment]
Changing line 468 javascript-source/init.js from
`if (isReady === false command.equalsIgnoreCase(bot) args[0].equalsIgnoreCase('moderate')) {
$.session.getModerationStatus();
}
`
To:
`if (isReady === false command.equalsIgnoreCase($.botName) args[0].equalsIgnoreCase('moderate')) { 
$.session.getModerationStatus();
}`


Fixed the issue for me not sure if its the intended fix here but as far as i can see bot is defined nowhere
