### ISSUE TITLE
"bot" is not defined

### ISSUE THREAD

**Issue by Cinux90** [PhantomBot/PhantomBot#2482]
PhantomBot Version: 3.4.2-arm
O/S Version: Raspbian GNU/Linux 10 (buster)
Java Version:11.0.11+9-1~deb10u1
Web Browser Version (if Panel related): 80.0.1

Detailed Description:
My Phantombot runs 24/7 on a Raspberrypi 3b. Today while a stream I face the issue that the bot no longer works.
Also a reboot not fixed the issue.
See below logentries

Steps to Reproduce:
Unknown, maybe still run phantombot 24/7

Logs:
```
May 31 20:28:55 raspberrypi launch-service.sh[1330]: [05-31-2021 @ 19:28:55.319 GMT] [ERROR] [onEvent()@ScriptEventManager.java:79] Failed to dispatch event tv.phantombot.event.command.CommandEvent
May 31 20:28:55 raspberrypi launch-service.sh[1330]: org.mozilla.javascript.EcmaError: ReferenceError: "bot" is not defined. (init.js#468)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4236)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4214)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4304)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1990)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1929)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.gen.init_js_1._c_anonymous_27(init.js:468)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.gen.init_js_1.call(init.js)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.gen.init_js_1.call(init.js)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.Context.call(Context.java:559)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at com.sun.proxy.$Proxy17.handle(Unknown Source)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at tv.phantombot.script.ScriptEventManager.onEvent(ScriptEventManager.java:75)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at tv.phantombot.twitch.irc.TwitchWSIRCParser.parseCommand(TwitchWSIRCParser.java:334)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at tv.phantombot.twitch.irc.TwitchWSIRCParser.onPrivMsg(TwitchWSIRCParser.java:395)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at tv.phantombot.twitch.irc.TwitchWSIRCParser.parseLine(TwitchWSIRCParser.java:311)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at tv.phantombot.twitch.irc.TwitchWSIRCParser.parseData(TwitchWSIRCParser.java:173)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at tv.phantombot.twitch.irc.TwitchWSIRC.lambda$onMessage$1(TwitchWSIRC.java:197)
May 31 20:28:55 raspberrypi launch-service.sh[1330]:         at java.base/java.lang.Thread.run(Thread.java:829)
May 31 20:28:55 raspberrypi launch-service.sh[1330]: [05-31-2021 @ 19:28:55.329 GMT] [DEBUG] [println()@debug.java:50] Dispatched event IrcModerationEvent
May 31 20:28:55 raspberrypi launch-service.sh[1330]: [05-31-2021 @ 19:28:55.356 GMT] [DEBUG] [println()@debug.java:50] Dispatched event IrcChannelMessageEvent
May 31 20:28:55 raspberrypi launch-service.sh[1330]: [05-31-2021 @ 19:28:55.359 GMT] [DEBUG] [println()@debug.java:50] IRCv3 Tags: {user-type=broadcaster, client-nonce=d1ebf5476caf27c5766ace1ab003e296, tmi-sent-ts=1622489335127, subscriber=0, mod=0, color=#00FF7F, turbo=0, user-id=71154433, flags=, premium=0, room-id=71154433, display-name=<name>, emotes=, id=1dbad78e-eb31-45be-ba30-fd32adc35f49, vip=0, badge-info=}
May 31 20:29:03 raspberrypi launch-service.sh[1330]: [05-31-2021 @ 19:29:03.432 GMT] [DEBUG] [println()@debug.java:50] Got a PING from Twitch Host Data Feed
```

**Comment by Sartharon** [comment]
Fixed with commit:
[aae148d](https://github.com/PhantomBot/PhantomBot/commit/aae148d03808dd856dd54580ce4bb9a587520139)

**Comment by gmt2001** [comment]
This was fixed in the above referenced commit, which is currently available in the nightly build

**Comment by gmt2001** [comment]
If you want to immediately grab the fix without switching to nightly, you can manually replace the file `PhantomBot/scripts/init.js` with the contents from https://raw.githubusercontent.com/PhantomBot/PhantomBot/aae148d03808dd856dd54580ce4bb9a587520139/javascript-source/init.js

**Comment by Cinux90** [comment]
Wow i have not expect that the answer/help will provided that much fast. Thank you for that.
As far as i have tested (replace the init.js file with the file provided by gmt2001) looks fine and works. :+1:
