### ISSUE TITLE
Bot stops working after a few hours of running.

### ISSUE THREAD

**Issue by AddisonMorris** [PhantomBot/PhantomBot#2573]
PhantomBot Version: v3.4.7
O/S Version: Windows server 2012 R2
Java Version: Java 8 update 301
Web Browser Version (if Panel related): edge

Detailed Description: I start the bot on my windows server and everything is fine. It will posts all logs and live alerts in discord. But by the time the streamer stops streaming it is stuck. The bot will not update the live or offline alert. It is really annoying for him to be offline for hours and it still say hes online.

Steps to Reproduce: When i restart the bot it fixes the issue temporarily till its stuck again. even if i was to restart it after he is offline it gets stuck before he goes live again and it does not show live alerts or anything. another restart fixes it for a few. super annoying. 

Logs: There are a few not sure if they are related,

[10-16-2021 @ 00:00:33.479 GMT] org.json.JSONException: JSONObject["banner"] is not a string.
	at org.json.JSONObject.wrongValueFormatException(JSONObject.java:2590)
	at org.json.JSONObject.getString(JSONObject.java:863)
	at com.gmt2001.TwitchAPIv5.getChannelTeams(TwitchAPIv5.java:990)
	at tv.phantombot.cache.TwitchTeamsCache.updateCache(TwitchTeamsCache.java:91)
	at tv.phantombot.cache.TwitchTeamsCache.run(TwitchTeamsCache.java:74)
	at java.base/java.lang.Thread.run(Unknown Source),

[08-31-2021 @ 21:40:42.175 GMT] java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at tv.phantombot.cache.TwitchCache.updateClips(TwitchCache.java:199)
	at tv.phantombot.cache.TwitchCache.run(TwitchCache.java:153)
	at java.base/java.lang.Thread.run(Unknown Source)

	

Screenshots (if applicable):

**Comment by gmt2001** [comment]
Online detection should be fixed in nightly. I'll look into that Exception

**Comment by AddisonMorris** [comment]
So i should switch to nightly?

**Comment by gmt2001** [comment]
To fix the online detection, yes. There should also be some other improvements. Do note that if you switch to nightly it will start automatically sending Exceptions to me via Rollbar unless you opt out before starting the bot. You should read the notice about it in the readme on the _code_ tab in GitHub if you have any privacy concerns
