### ISSUE TITLE
Stage channels kill D4J operations

### ISSUE THREAD

**Issue by gmt2001** [PhantomBot/PhantomBot#2593]
[11-20-2021 @ 08:16:34.580 GMT] java.lang.UnsupportedOperationException: Unknown Value: ChannelData{id=848799434279354379, type=13, guildId=Possible{412125474865807360}, position=Possible{4}, permissionOverwrites=[OverwriteData{id=412125474865807360, type=role, allow=0, deny=0}, OverwriteData{id=803439320911446016, type=role, allow=1048576, deny=0}, OverwriteData{id=816600287598477314, type=role, allow=0, deny=2099264}, OverwriteData{id=838303911244857394, type=role, allow=0, deny=0}], name=Possible{Music - Rythm}, topic=Possible{Optional.empty}, nsfw=Possible.absent, lastMessageId=Possible.absent, bitrate=Possible{40000}, userLimit=Possible{10000}, rateLimitPerUser=Possible.absent, recipients=null, icon=Possible.absent, ownerId=Possible.absent, applicationId=Possible.absent, parentId=Possible{Optional[838342559578324992]}, lastPinTimestamp=Possible.absent}
	at discord4j.core.util.EntityUtil.throwUnsupportedDiscordValue(EntityUtil.java:76)
	at discord4j.core.util.EntityUtil.getChannel(EntityUtil.java:63)
	at discord4j.core.retriever.StoreEntityRetriever.lambda$null$12(StoreEntityRetriever.java:114)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:704)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:970)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:267)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8325)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2317)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:134)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
	at reactor.core.publisher.Mono.block(Mono.java:1677)
	at tv.phantombot.discord.util.DiscordUtil.sendMessageEmbed(DiscordUtil.java:284)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:55)
	at org.mozilla.javascript.gen.followHandler_js_169._c_anonymous_4(followHandler.js:60)
	at org.mozilla.javascript.gen.followHandler_js_169.call(followHandler.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:45)
	at org.mozilla.javascript.gen.init_js_1._c_callHook_21(init.js:318)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:76)
	at org.mozilla.javascript.gen.init_js_1._c_anonymous_31(init.js:636)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:559)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy10.handle(Unknown Source)
	at tv.phantombot.script.ScriptEventManager.onEvent(ScriptEventManager.java:75)
	at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:29)
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:42)
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:72)
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:49)
	at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:67)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1678)
		... 37 more

[11-20-2021 @ 19:13:19.527 GMT] java.lang.UnsupportedOperationException: Unknown Value: ChannelData{id=848799434279354379, type=13, guildId=Possible{412125474865807360}, position=Possible{4}, permissionOverwrites=[OverwriteData{id=412125474865807360, type=role, allow=0, deny=0}, OverwriteData{id=803439320911446016, type=role, allow=1048576, deny=0}, OverwriteData{id=816600287598477314, type=role, allow=0, deny=2099264}, OverwriteData{id=838303911244857394, type=role, allow=0, deny=0}], name=Possible{Music - Rythm}, topic=Possible{Optional.empty}, nsfw=Possible.absent, lastMessageId=Possible.absent, bitrate=Possible{40000}, userLimit=Possible{10000}, rateLimitPerUser=Possible.absent, recipients=null, icon=Possible.absent, ownerId=Possible.absent, applicationId=Possible.absent, parentId=Possible{Optional[838342559578324992]}, lastPinTimestamp=Possible.absent}
	at discord4j.core.util.EntityUtil.throwUnsupportedDiscordValue(EntityUtil.java:76)
	at discord4j.core.util.EntityUtil.getChannel(EntityUtil.java:63)
	at discord4j.core.retriever.StoreEntityRetriever.lambda$null$12(StoreEntityRetriever.java:114)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:704)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:970)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:267)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8325)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2317)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:134)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
	at reactor.core.publisher.Mono.block(Mono.java:1677)
	at tv.phantombot.discord.util.DiscordUtil.sendMessageEmbed(DiscordUtil.java:284)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:55)
	at org.mozilla.javascript.gen.followHandler_js_169._c_anonymous_4(followHandler.js:60)
	at org.mozilla.javascript.gen.followHandler_js_169.call(followHandler.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:45)
	at org.mozilla.javascript.gen.init_js_1._c_callHook_21(init.js:318)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:76)
	at org.mozilla.javascript.gen.init_js_1._c_anonymous_31(init.js:636)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:559)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy10.handle(Unknown Source)
	at tv.phantombot.script.ScriptEventManager.onEvent(ScriptEventManager.java:75)
	at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:29)
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:42)
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:72)
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:49)
	at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:67)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1678)
		... 37 more

[11-20-2021 @ 19:14:04.032 GMT] java.lang.UnsupportedOperationException: Unknown Value: ChannelData{id=848799434279354379, type=13, guildId=Possible{412125474865807360}, position=Possible{4}, permissionOverwrites=[OverwriteData{id=412125474865807360, type=role, allow=0, deny=0}, OverwriteData{id=803439320911446016, type=role, allow=1048576, deny=0}, OverwriteData{id=816600287598477314, type=role, allow=0, deny=2099264}, OverwriteData{id=838303911244857394, type=role, allow=0, deny=0}], name=Possible{Music - Rythm}, topic=Possible{Optional.empty}, nsfw=Possible.absent, lastMessageId=Possible.absent, bitrate=Possible{40000}, userLimit=Possible{10000}, rateLimitPerUser=Possible.absent, recipients=null, icon=Possible.absent, ownerId=Possible.absent, applicationId=Possible.absent, parentId=Possible{Optional[838342559578324992]}, lastPinTimestamp=Possible.absent}
	at discord4j.core.util.EntityUtil.throwUnsupportedDiscordValue(EntityUtil.java:76)
	at discord4j.core.util.EntityUtil.getChannel(EntityUtil.java:63)
	at discord4j.core.retriever.StoreEntityRetriever.lambda$null$12(StoreEntityRetriever.java:114)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:704)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:970)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:267)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8325)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2317)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:134)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
	at reactor.core.publisher.Mono.block(Mono.java:1677)
	at tv.phantombot.discord.util.DiscordUtil.sendMessageEmbed(DiscordUtil.java:284)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:55)
	at org.mozilla.javascript.gen.followHandler_js_169._c_anonymous_4(followHandler.js:60)
	at org.mozilla.javascript.gen.followHandler_js_169.call(followHandler.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:45)
	at org.mozilla.javascript.gen.init_js_1._c_callHook_21(init.js:318)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:76)
	at org.mozilla.javascript.gen.init_js_1._c_anonymous_31(init.js:636)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:559)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy10.handle(Unknown Source)
	at tv.phantombot.script.ScriptEventManager.onEvent(ScriptEventManager.java:75)
	at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:29)
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:42)
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:72)
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:49)
	at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:67)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1678)
		... 37 more

[11-20-2021 @ 19:15:00.457 GMT] java.lang.UnsupportedOperationException: Unknown Value: ChannelData{id=848799434279354379, type=13, guildId=Possible{412125474865807360}, position=Possible{4}, permissionOverwrites=[OverwriteData{id=412125474865807360, type=role, allow=0, deny=0}, OverwriteData{id=803439320911446016, type=role, allow=1048576, deny=0}, OverwriteData{id=816600287598477314, type=role, allow=0, deny=2099264}, OverwriteData{id=838303911244857394, type=role, allow=0, deny=0}], name=Possible{Music - Rythm}, topic=Possible{Optional.empty}, nsfw=Possible.absent, lastMessageId=Possible.absent, bitrate=Possible{40000}, userLimit=Possible{10000}, rateLimitPerUser=Possible.absent, recipients=null, icon=Possible.absent, ownerId=Possible.absent, applicationId=Possible.absent, parentId=Possible{Optional[838342559578324992]}, lastPinTimestamp=Possible.absent}
	at discord4j.core.util.EntityUtil.throwUnsupportedDiscordValue(EntityUtil.java:76)
	at discord4j.core.util.EntityUtil.getChannel(EntityUtil.java:63)
	at discord4j.core.retriever.StoreEntityRetriever.lambda$null$12(StoreEntityRetriever.java:114)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:704)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:970)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:267)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8325)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2317)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:134)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
	at reactor.core.publisher.Mono.block(Mono.java:1677)
	at tv.phantombot.discord.util.DiscordUtil.sendMessageEmbed(DiscordUtil.java:284)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:55)
	at org.mozilla.javascript.gen.followHandler_js_169._c_anonymous_4(followHandler.js:60)
	at org.mozilla.javascript.gen.followHandler_js_169.call(followHandler.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:45)
	at org.mozilla.javascript.gen.init_js_1._c_callHook_21(init.js:318)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:76)
	at org.mozilla.javascript.gen.init_js_1._c_anonymous_31(init.js:636)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:559)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy10.handle(Unknown Source)
	at tv.phantombot.script.ScriptEventManager.onEvent(ScriptEventManager.java:75)
	at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:29)
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:42)
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:72)
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:49)
	at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:67)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1678)
		... 37 more

**Comment by gmt2001** [comment]
I believe this was fixed already by updating D4J in nightly and the RC
