### ISSUE TITLE
Timer and all settings cannot be changed via the panel.

### ISSUE THREAD

**Issue by TonyOneZero** [PhantomBot/PhantomBot#2630]
PhantomBot Version: 3.5.0.4
O/S Version: Linux
Java Version: 11.0.10+9
Web Browser Version (if Panel related): 1.5.0

Detailed Description:
Timer and all settings cannot be changed via the panel. As soon as you want to turn the timer off or on, the switch moves only very briefly and then returns to its original position. 

The alerts cannot be turned off. There you can operate the switches, but after a refresh (F5) all alerts remain on. There are no error messages in the console.

Steps to Reproduce:
Ubuntu 20
wget + unzip
SSL over Reverse Proxy https://phantombot.github.io/PhantomBot/guides/#guide=content/integrations/twitchembeds&jumpto=method-3-setup-a-reverse-proxy

Logs:
```
There are no error messages in the console.
[12-17-2021 @ 17:11:28.855 GMT] PhantomBot Version: 3.5.0 (stable)
[12-17-2021 @ 17:11:28.856 GMT] Build Revision: d7a5c2c
[12-17-2021 @ 17:11:28.856 GMT] Creator: mast3rplan
[12-17-2021 @ 17:11:28.856 GMT] Developers: gmt2001, Kojitsari, ScaniaTV, & IllusionaryOne
[12-17-2021 @ 17:11:28.856 GMT] https://phantombot.github.io/PhantomBot/
[12-17-2021 @ 17:11:28.857 GMT] 
[12-17-2021 @ 17:11:30.292 GMT] Validated Twitch CHAT (oauth) OAUTH Token.
[12-17-2021 @ 17:11:30.294 GMT] Validated Twitch API (apioauth) OAUTH Token.
[12-17-2021 @ 17:11:30.473 GMT] 
[12-17-2021 @ 17:11:31.309 GMT] Loaded module: core/misc.js (Enabled)
[12-17-2021 @ 17:11:31.335 GMT] Loaded module: core/jsTimers.js (Enabled)
[12-17-2021 @ 17:11:31.381 GMT] Loaded module: core/updates.js (Enabled)
[12-17-2021 @ 17:11:31.498 GMT] Loaded module: core/commandTags.js (Enabled)
[12-17-2021 @ 17:11:31.733 GMT] Loaded module: core/chatModerator.js (Enabled)
[12-17-2021 @ 17:11:31.778 GMT] Loaded module: core/fileSystem.js (Enabled)
[12-17-2021 @ 17:11:32.225 GMT] Loaded module: core/lang.js (Enabled)
[12-17-2021 @ 17:11:32.231 GMT] Loaded module: core/commandPause.js (Enabled)
[12-17-2021 @ 17:11:32.275 GMT] Loaded module: core/logging.js (Enabled)
[12-17-2021 @ 17:11:32.306 GMT] Loaded module: core/commandRegister.js (Enabled)
[12-17-2021 @ 17:11:32.313 GMT] Loaded module: core/whisper.js (Enabled)
[12-17-2021 @ 17:11:32.324 GMT] Loaded module: core/commandCoolDown.js (Enabled)
[12-17-2021 @ 17:11:32.328 GMT] Loaded module: core/keywordCoolDown.js (Enabled)
[12-17-2021 @ 17:11:32.380 GMT] Loaded module: core/patternDetector.js (Enabled)
[12-17-2021 @ 17:11:32.404 GMT] Loaded module: core/permissions.js (Enabled)
[12-17-2021 @ 17:11:32.427 GMT] Loaded module: commands/customCommands.js (Enabled)
[12-17-2021 @ 17:11:32.473 GMT] Loaded module: commands/nameConverter.js (Enabled)
[12-17-2021 @ 17:11:32.533 GMT] Loaded module: commands/highlightCommand.js (Enabled)
[12-17-2021 @ 17:11:32.576 GMT] Loaded module: commands/deathctrCommand.js (Enabled)
[12-17-2021 @ 17:11:32.589 GMT] Loaded module: commands/dualstreamCommand.js (Enabled)
[12-17-2021 @ 17:11:32.631 GMT] Loaded module: commands/topCommand.js (Enabled)
[12-17-2021 @ 17:11:32.783 GMT] Loaded module: commands/lastseenCommand.js (Enabled)
[12-17-2021 @ 17:11:32.795 GMT] Loaded module: commands/streamCommand.js (Enabled)
[12-17-2021 @ 17:11:32.817 GMT] Loaded module: games/killCommand.js (Enabled)
[12-17-2021 @ 17:11:32.825 GMT] Loaded module: games/8ball.js (Enabled)
[12-17-2021 @ 17:11:32.890 GMT] Loaded module: games/gambling.js (Enabled)
[12-17-2021 @ 17:11:32.897 GMT] Loaded module: games/roulette.js (Enabled)
[12-17-2021 @ 17:11:32.915 GMT] Loaded module: games/adventureSystem.js (Enabled)
[12-17-2021 @ 17:11:32.924 GMT] Loaded module: games/slotMachine.js (Enabled)
[12-17-2021 @ 17:11:32.932 GMT] Loaded module: games/roll.js (Enabled)
[12-17-2021 @ 17:11:32.935 GMT] Loaded module: games/random.js (Enabled)
[12-17-2021 @ 17:11:32.976 GMT] Loaded module: handlers/wordCounter.js (Enabled)
[12-17-2021 @ 17:11:32.983 GMT] Loaded module: handlers/bitsHandler.js (Enabled)
[12-17-2021 @ 17:11:32.989 GMT] Loaded module: handlers/clipHandler.js (Enabled)
[12-17-2021 @ 17:11:33.011 GMT] Loaded module: handlers/channelPointsHandler.js (Enabled)
[12-17-2021 @ 17:11:33.021 GMT] Loaded module: handlers/tipeeeStreamHandler.js (Enabled)
[12-17-2021 @ 17:11:33.031 GMT] Loaded module: handlers/followHandler.js (Enabled)
[12-17-2021 @ 17:11:33.036 GMT] Loaded module: handlers/gameScanHandler.js (Enabled)
[12-17-2021 @ 17:11:33.043 GMT] Loaded module: handlers/donationHandler.js (Enabled)
[12-17-2021 @ 17:11:33.095 GMT] Loaded module: handlers/subscribeHandler.js (Enabled)
[12-17-2021 @ 17:11:33.101 GMT] Loaded module: handlers/emotesHandler.js (Enabled)
[12-17-2021 @ 17:11:33.108 GMT] Loaded module: handlers/keywordHandler.js (Enabled)
[12-17-2021 @ 17:11:33.117 GMT] Loaded module: handlers/hostHandler.js (Enabled)
[12-17-2021 @ 17:11:33.134 GMT] Loaded module: handlers/streamElementsHandler.js (Enabled)
[12-17-2021 @ 17:11:33.177 GMT] Loaded module: handlers/raidHandler.js (Enabled)
[12-17-2021 @ 17:11:33.196 GMT] Loaded module: handlers/twitterHandler.js (Enabled)
[12-17-2021 @ 17:11:33.202 GMT] Loaded module: core/gameMessages.js (Enabled)
[12-17-2021 @ 17:11:33.211 GMT] Loaded module: core/panelHandler.js (Enabled)
[12-17-2021 @ 17:11:33.221 GMT] Loaded module: core/panelCommands.js (Enabled)
[12-17-2021 @ 17:11:33.234 GMT] Loaded module: core/initCommands.js (Enabled)
[12-17-2021 @ 17:11:33.282 GMT] Loaded module: core/timeSystem.js (Enabled)
[12-17-2021 @ 17:11:33.286 GMT] Loaded module: core/coreCommands.js (Enabled)
[12-17-2021 @ 17:11:33.291 GMT] Loaded module: core/lockdown.js (Enabled)
[12-17-2021 @ 17:11:33.303 GMT] Loaded module: core/streamInfo.js (Enabled)
[12-17-2021 @ 17:11:33.312 GMT] Loaded module: systems/queueSystem.js (Enabled)
[12-17-2021 @ 17:11:33.318 GMT] Loaded module: systems/cleanupSystem.js (Enabled)
[12-17-2021 @ 17:11:33.324 GMT] Loaded module: systems/greetingSystem.js (Enabled)
[12-17-2021 @ 17:11:33.333 GMT] Loaded module: systems/quoteSystem.js (Enabled)
[12-17-2021 @ 17:11:33.340 GMT] Loaded module: systems/auctionSystem.js (Enabled)
[12-17-2021 @ 17:11:33.386 GMT] Loaded module: systems/raffleSystem.js (Enabled)
[12-17-2021 @ 17:11:33.393 GMT] Loaded module: systems/commercialSystem.js (Enabled)
[12-17-2021 @ 17:11:33.402 GMT] Loaded module: systems/audioPanelSystem.js (Enabled)
[12-17-2021 @ 17:11:33.415 GMT] Loaded module: systems/bettingSystem.js (Enabled)
[12-17-2021 @ 17:11:33.428 GMT] Loaded module: systems/pollSystem.js (Enabled)
[12-17-2021 @ 17:11:33.484 GMT] Loaded module: systems/noticeSystem.js (Enabled)
[12-17-2021 @ 17:11:33.496 GMT] Loaded module: systems/ticketraffleSystem.js (Enabled)
[12-17-2021 @ 17:11:33.504 GMT] Loaded module: systems/ranksSystem.js (Enabled)
[12-17-2021 @ 17:11:33.575 GMT] Loaded module: systems/youtubePlayer.js (Enabled)
[12-17-2021 @ 17:11:33.584 GMT] Loaded module: systems/welcomeSystem.js (Disabled)
[12-17-2021 @ 17:11:33.603 GMT] Loaded module: systems/pointSystem.js (Enabled)
[12-17-2021 @ 17:11:33.609 GMT] 
[12-17-2021 @ 17:11:33.609 GMT] For support please visit: https://discord.gg/YKvMd78
[12-17-2021 @ 17:11:33.609 GMT] 
[12-17-2021 @ 17:11:33.635 GMT] Connecting to Twitch WS-IRC Server (SSL) [irc-ws.chat.twitch.tv]
[12-17-2021 @ 17:11:34.413 GMT] Connected to keinmodaberbot@irc-ws.chat.twitch.tv (SSL)
[12-17-2021 @ 17:11:34.623 GMT] Channel Joined [#clym]
[12-17-2021 @ 17:11:35.033 GMT] Connected to Twitch Host Data Feed
[12-17-2021 @ 17:11:36.333 GMT] Connected to Twitch Moderation Data Feed
[12-17-2021 @ 17:11:36.335 GMT] Connected to Twitch Channel Points Data Feed
[12-17-2021 @ 17:11:36.335 GMT] Connected to Twitch Stream Up/Down Data Feed
[12-17-2021 @ 17:11:36.336 GMT] Connected to Twitch Follow Data Feed
[12-17-2021 @ 17:11:55.034 GMT] >> Enabling hosts announcements
[12-17-2021 @ 17:11:55.643 GMT] >> Enabling follower announcements

```

Screenshots (if applicable):

https://user-images.githubusercontent.com/15279954/146583789-4b3d664b-3fe5-41bf-8c64-40db90841ffc.mp4

https://user-images.githubusercontent.com/15279954/146583810-a44ae5c9-490b-4a67-a46e-f2e0b58d5962.mp4

**Comment by gmt2001** [comment]
Check core-error log. Some errors only show in the log file

**Comment by TonyOneZero** [comment]
@gmt2001 
I took a closer look at the log files. This is the only thing I could find.

core-error Log
```
[12-17-2021 @ 17:11:33.927 GMT] org.json.JSONException: JSONArray[5] not found.
	at org.json.JSONArray.get(JSONArray.java:225)
	at org.json.JSONArray.getJSONObject(JSONArray.java:438)
	at com.illusionaryone.GitHubAPIv3.CheckNewRelease(GitHubAPIv3.java:204)
	at tv.phantombot.PhantomBot.lambda$doCheckPhantomBotUpdate$2(PhantomBot.java:1410)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gmt2001** [comment]
Try running `!module disable ./handlers/bitsHandler.js` from Twitch chat and see if that sticks

**Comment by gmt2001** [comment]
Also I forgot that the plain `logs/error` folder should also be checked just to be sure, that one does script errors

**Comment by TonyOneZero** [comment]
I was able to solve it myself. The bot was not shut down properly by a script and the database was apparently not unlocked because of this.

**Comment by TonyOneZero** [comment]
@gmt2001 Error reappears and seems to be related to a of the streamer name in the config. If I change the channel name from "clym" to "tonyonezero10" everything works fine. 

botlogin.txt Bot does not work
```
channel=clym
```

botlogin.txt Bot works
```
channel=tonyonezero10
```

The bot is for the streamer called "Clym" though, can someone take a look at that?

**Comment by TonyOneZero** [comment]
Ok this is very embarrassing for me. But it should perhaps also be included in the FAQ or in the guides. The described behavior occurs in every channel as long as the bot does not have moderator rights.

**Comment by gmt2001** [comment]
It is planned to rewrite the guides. Most were community contributions, copied from the old website, and left much to be desired.

gmt2001/PhantomBot-1#161
