### ISSUE TITLE
[Bug] Saving language files does not work.

### ISSUE THREAD

**Issue by ElTomat** [PhantomBot/PhantomBot#2638]
PhantomBot Version: 3.5.0.6 (stable) (Revision: 0104f39)
O/S Version: Debian 10
Java Version: 11.0.13+8-post-Debian-1deb10u1
Web Browser Version (if Panel related): 1.5.0

Detailed Description:
Saving language files does not work.
After editing the file and pressing the save button, nothing happens in the panel.

Steps to Reproduce:
1. Open any file in the language file editor
2. Edit language file
3. Click the save button

Logs:
`java.nio.file.FileSystemException: ./scripts/lang/custom: Is a directory
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
	at java.base/java.nio.file.Files.write(Files.java:3425)
	at com.scaniatv.LangFileUpdater.updateCustomLang(LangFileUpdater.java:122)
	at tv.phantombot.panel.WsPanelHandler.handleRemote(WsPanelHandler.java:340)
	at tv.phantombot.panel.WsPanelHandler.handleUnrestrictedCommands(WsPanelHandler.java:273)
	at tv.phantombot.panel.WsPanelHandler.handleFrame(WsPanelHandler.java:98)
	at com.gmt2001.httpwsserver.WebSocketFrameHandler.channelRead0(WebSocketFrameHandler.java:79)
	at com.gmt2001.httpwsserver.WebSocketFrameHandler.channelRead0(WebSocketFrameHandler.java:45)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

**Comment by gmt2001** [comment]
LangFileUpdater using var out of scope, use in-scope var

https://github.com/PhantomBot/PhantomBot/blob/0104f39479d520047d38140219f60d218e1474b0/resources/web/panel/js/pages/settings/localization.js#L29

https://github.com/PhantomBot/PhantomBot/blob/0104f39479d520047d38140219f60d218e1474b0/resources/web/panel/js/pages/settings/localization.js#L31

https://github.com/PhantomBot/PhantomBot/blob/0104f39479d520047d38140219f60d218e1474b0/resources/web/panel/js/pages/settings/localization.js#L118

Rewrite path sanitizer, exists, mkdir

https://github.com/PhantomBot/PhantomBot/blob/0104f39479d520047d38140219f60d218e1474b0/source/com/scaniatv/LangFileUpdater.java#L102

https://github.com/PhantomBot/PhantomBot/blob/0104f39479d520047d38140219f60d218e1474b0/source/com/scaniatv/LangFileUpdater.java#L108-L119

refs rb#1047
refs rb#1048
