### ISSUE TITLE
java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "tv.phantombot.cache.FollowersCache

### ISSUE THREAD

**Issue by Raukgorth** [PhantomBot/PhantomBot#2653]
PhantomBot Version: 3.5.0.8
O/S Version: Windows 10
Java Version: Java 11.0.11
Web Browser Version (if Panel related):

Detailed Description:
The bot threw an exception when his install location was temporarily not available (~5 minutes).
After shutting down and restarting it asks for login name and OAuth as the botlogin.txt file was blank.

Steps to Reproduce: 
1. Install bot on a shared network drive.
2. Start the bot on a machine running 24/7
3. Shared drive has to restart due to updates
4. Above error occurs.

Logs:
```
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "tv.phantombot.cache.FollowersCache"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Timer-5"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "tv.phantombot.cache.TwitchCache"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Timer-6"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "scripts::systems::timeSystem.js#1"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "tv.phantombot.cache.EmotesCache"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"
[01-25-2022 @ 12:18:04.016 GMT] Refreshed the broadcaster token

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"
[01-25-2022 @ 14:18:04.103 GMT] Refreshed the bot token

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"
[01-25-2022 @ 16:33:03.997 GMT] Refreshed the broadcaster token

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"
java.lang.NullPointerException
        at tv.phantombot.event.ExceptionHandler.handleError(ExceptionHandler.java:26)
        at net.engio.mbassy.bus.AbstractPubSubSupport.handlePublicationError(AbstractPubSubSupport.java:106)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:72)
        at java.base/java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at tv.phantombot.event.ExceptionHandler.handleError(ExceptionHandler.java:26)
        at net.engio.mbassy.bus.AbstractPubSubSupport.handlePublicationError(AbstractPubSubSupport.java:106)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:72)
        at java.base/java.lang.Thread.run(Unknown Source)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"
java.lang.NullPointerException
        at tv.phantombot.event.ExceptionHandler.handleError(ExceptionHandler.java:26)
        at net.engio.mbassy.bus.AbstractPubSubSupport.handlePublicationError(AbstractPubSubSupport.java:106)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:72)
        at java.base/java.lang.Thread.run(Unknown Source)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "core::permissions.js::ircChannelUsersUpdate"
java.lang.NullPointerException
        at tv.phantombot.event.ExceptionHandler.handleError(ExceptionHandler.java:26)
        at net.engio.mbassy.bus.AbstractPubSubSupport.handlePublicationError(AbstractPubSubSupport.java:106)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:72)
        at java.base/java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at tv.phantombot.event.ExceptionHandler.handleError(ExceptionHandler.java:26)
        at net.engio.mbassy.bus.AbstractPubSubSupport.handlePublicationError(AbstractPubSubSupport.java:106)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:72)
        at java.base/java.lang.Thread.run(Unknown Source)

[01-25-2022 @ 17:47:35.759 GMT] rauk_bot is shutting down...
[01-25-2022 @ 17:47:35.760 GMT] Sending the shutdown event to scripts...
java.lang.NullPointerException[01-25-2022 @ 17:48:04.024 GMT] Refreshed the bot token

        at tv.phantombot.event.ExceptionHandler.handleError(ExceptionHandler.java:26)
        at net.engio.mbassy.bus.AbstractPubSubSupport.handlePublicationError(AbstractPubSubSupport.java:106)
        at net.engio.mbassy.bus.MBassador.publish(MBassador.java:68)
        at tv.phantombot.event.EventBus.post(EventBus.java:72)
        at tv.phantombot.PhantomBot.onExit(PhantomBot.java:1041)
        at tv.phantombot.PhantomBot.lambda$init$0(PhantomBot.java:1008)
        at java.base/java.lang.Thread.run(Unknown Source)
[01-25-2022 @ 17:48:16.410 GMT] Stopping all events and message dispatching...

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "tv.phantombot.PhantomBot::onExit"
Terminate batch job (Y/N)?
```

Screenshots (if applicable):

**Comment by gmt2001** [comment]
Try re-installing the latest version to a separate folder, only copy over the config folder. Also, make sure you use the launcher scripts to start the bot. This usually happens due to file permissions or corrupt PhantomBot.jar

**Comment by Raukgorth** [comment]
Hey gmt2001. Thanks for pointing me to the correct source of the issue. I have updated the original post with:

Detailed Description:
The bot threw an exception when his install location was temporarily not available (~5 minutes).
After shutting down and restarting it asks for login name and OAuth as the botlogin.txt file was blank.

Steps to Reproduce:

    Install bot on a shared network drive.
    Start the bot on a machine running 24/7
    Shared drive has to restart due to updates
    Above error occurs.
