### ISSUE TITLE
Twitter Integration not working correctly

### ISSUE THREAD

**Issue by Alucard2112** [PhantomBot/PhantomBot#2693]
PhantomBot Version: 3.5.2 (stable)
Operating System: Linux
Java Version: 11.0.14+9
Web Browser Version (if Panel related):

Detailed Description:
The bot does not post on Twitter whenever I go live.

Steps to Reproduce:
Setting up Twitter and alerts, then go live.

Logs:
java.lang.NullPointerException
        at com.illusionaryone.TwitterAPI.updateStatus(TwitterAPI.java:190)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:206)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:211)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:35)
        at org.mozilla.javascript.gen.twitterHandler_js_119._c_anonymous_4(twitterHandler.js:136)
        at org.mozilla.javascript.gen.twitterHandler_js_119.call(twitterHandler.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:35)
        at org.mozilla.javascript.gen.init_js_1._c_callHook_21(init.js:332)
        at org.mozilla.javascript.gen.init_js_1.call(init.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:59)
        at org.mozilla.javascript.gen.init_js_1._c_anonymous_29(init.js:654)
        at org.mozilla.javascript.gen.init_js_1.call(init.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868)
        at org.mozilla.javascript.gen.init_js_1.call(init.js)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:166)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:116)
        at org.mozilla.javascript.Context.call(Context.java:535)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:472)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:116)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy12.handle(Unknown Source)
        at tv.phantombot.script.ScriptEventManager.onEvent(ScriptEventManager.java:77)
        at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:29)
        at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
        at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:42)
        at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:72)
        at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:49)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:67)
        at java.base/java.lang.Thread.run(Unknown Source)

Screenshots (if applicable):

**Comment by Alucard2112** [comment]
Later on, this happened and I had to restart the bot:
[init.js:340] Error with Event Handler [twitchOnline] Script [./core/streamInfo.js] Stacktrace [streamInfo.js:34 > init.js:332 > init.js:654] Exception [TypeError: Cannot call method "getGameTitle" of undefined]
Error with Event Handler [twitchOnline] Script [./handlers/twitterHandler.js] Stacktrace [twitterHandler.js:136 > init.js:332 > init.js:654] Exception [TypeError: Cannot call method "getStreamStatus" of undefined]

**Comment by MrGamy** [comment]
I encountered the same issue, which caused the bot to no longer reconnect to twitch chat / interact with the twitch api. The discord integration was - weirdly enough - unaffected. 
Only solution for now seems to be disabling the twitter integration by commenting out the twitter credentials inside botlogin.txt
