### ISSUE TITLE
ReferenceError in commands/default.js

### ISSUE THREAD

**Issue by gmt2001** [PhantomBot/PhantomBot#2750]
https://github.com/PhantomBot/PhantomBot/blob/1c15f6f1df59286e07def062eee9c98627170dc9/resources/web/panel/js/pages/commands/default.js#L203

[PhantomBot Error] Failed to run callback: (ReferenceError) commandName is not defined >> ReferenceError: commandName is not defined
    at <anonymous>:203:57
    at Object.func (<anonymous>:87:25)
    at a.webSocket.onmessage (<anonymous>:598:34)
    at HTMLDivElement.<anonymous> (https://bot:25000/common/reconnecting-websocket/reconnectingWS.min.js:30:836)
    at WebSocket.h.onmessage (https://bot:25000/common/reconnecting-websocket/reconnectingWS.min.js:30:2312)

**Comment by Sartharon** [comment]
Another occurrence was in default.js
Issue should be fully resolved with [this PR](https://github.com/PhantomBot/PhantomBot/pull/2755)
