### ISSUE TITLE
java.lang.ExceptionInInitializerError in startup of latest docker container

### ISSUE THREAD

**Issue by merspieler** [PhantomBot/PhantomBot#2756]
PhantomBot Version: 3.6.0.1
O/S Version: Debian Bullseye, running docker and podman (both with exactly the same error)
Java Version: 11.0.14.1
Web Browser Version (if Panel related):

Detailed Description:
Up on running
`docker run -it --name phantombot --hostname phantombot -v <path>:/opt/PhantomBot_data -p 25000:25000 -e PHANTOMBOT_USER=<username> -e PHANTOMBOT_OAUTH=<token> -e PHANTOMBOT_CHANNEL=<username> docker.io/gmt2001/phantombot-stable:3.6.0.1`
I get the following stack trace in the docker log.
```
[04-13-2022 @ 22:49:29.311 GMT] The working directory is: /opt/PhantomBot
[04-13-2022 @ 22:49:29.443 GMT] Detected Java 11.0.14.1 running on Linux 5.10.0-8-amd64 (amd64)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.gmt2001.Console.err.logStackTrace(err.java:144)
        at com.gmt2001.Console.err.printStackTrace(err.java:113)
        at com.gmt2001.Console.err.printStackTrace(err.java:105)
        at com.gmt2001.Console.err.printStackTrace(err.java:101)
        at com.gmt2001.Console.err.printStackTrace(err.java:85)
        at com.gmt2001.Console.err.printStackTrace(err.java:81)
        at tv.phantombot.CaselessProperties.store(CaselessProperties.java:251)
        at tv.phantombot.ConfigurationManager.getConfiguration(ConfigurationManager.java:158)
        at tv.phantombot.PhantomBot.main(PhantomBot.java:1332)
Caused by: java.lang.NullPointerException
        at com.gmt2001.Logger.instance(Logger.java:109)
        at com.gmt2001.Console.err.logStackTrace(err.java:144)
        at com.gmt2001.Console.err.printStackTrace(err.java:113)
        at com.gmt2001.Console.err.printStackTrace(err.java:105)
        at com.gmt2001.Console.err.printStackTrace(err.java:101)
        at com.gmt2001.Console.err.printStackTrace(err.java:85)
        at com.gmt2001.Console.err.printStackTrace(err.java:81)
        at com.gmt2001.Logger.lambda$new$0(Logger.java:130)
        at java.base/java.util.Map.forEach(Unknown Source)
        at com.gmt2001.Logger.<init>(Logger.java:126)
        at com.gmt2001.Logger.<clinit>(Logger.java:51)
        ... 9 more

```

Steps to Reproduce:
Start the container with the command above.

I've also tested this with podman with exactly the same result.

**Comment by gmt2001** [comment]
Host OS Permissions error due to non-standard volume configuration

Volume mount must be chown by 901:900

Will work on a patch so the correct Exception gets printed in the next release

**Comment by merspieler** [comment]
Thanks, will try in the evening and let you know

**Comment by merspieler** [comment]
Unfortunately, chown didn't do the trick. Neither does setting chmod 777. I can write to `/opt/PhantomBot_data/` in the container but the error persists.

**Comment by gmt2001** [comment]
The ExceptionInInitializerError should be gone in tomorrows nightly so you can see the real exception that is blocking you

**Comment by merspieler** [comment]
Running the nightly I've got the following error:
```
touch: cannot touch '/opt/PhantomBot_data/config/botlogin.txt': No such file or directory                                                
The data directory is not chown by the service user      
Please run the following command to fix this:                                                                                                                                                                                                                                     
   sudo docker exec --user root -it phantombot chown -R -H -L phantombot:phantombot /opt/PhantomBot_data
```
The dir had already the right owner, but the config dir didn't exists... creating that got me up and running. 
Maybe add a `mkdir -p /opt/PhantomBot_data/config` to make sure, that directory always exists

Thanks for your help
