### ISSUE TITLE
upgrade from 3.9.0.6 to 3.10.0.10 database fails upgrade so no logins.

### ISSUE THREAD

**Issue by Freejack01** [PhantomBot/PhantomBot#3404]
PhantomBot Version: 3.10.0.10
O/S Version:Linux Mint 21 / Ubuntu 22.04
Java Version: openjdk version "11.0.20.1"
Web Browser Version (if Panel related):

Detailed Description:
database fails upgrade tried both full and lin verrsion from github.

Steps to Reproduce:
Upgrade from 3.9.0.6 to 3.10.0.10

Logs:
09-17-2023 @ 20:43:30.151 GMT] [startUpgrade()@H2Store2.java:170] java.nio.file.NoSuchFileException: ./dbbackup/phantombot.h2.mv.db
[09-17-2023 @ 20:43:30.154 GMT] [startUpgrade()@H2Store2.java:170]
java.nio.file.NoSuchFileException: ./dbbackup/phantombot.h2.mv.db
at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
at java.base/sun.nio.fs.UnixCopyFile.copyFile(Unknown Source)
at java.base/sun.nio.fs.UnixCopyFile.copy(Unknown Source)
at java.base/sun.nio.fs.UnixFileSystemProvider.copy(Unknown Source)
at java.base/java.nio.file.Files.copy(Unknown Source)
at com.gmt2001.datastore2.H2Store2.startUpgrade(H2Store2.java:167)
at com.gmt2001.datastore2.H2Store2.(H2Store2.java:95)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at com.gmt2001.datastore2.Datastore2.init(Datastore2.java:226)
at com.gmt2001.datastore2.Datastore2.init(Datastore2.java:150)
at tv.phantombot.PhantomBot.(PhantomBot.java:336)
at tv.phantombot.PhantomBot.main(PhantomBot.java:1182)

Screenshots (if applicable):

**Comment by gmt2001** [comment]
Please create a `dbbackup` directory inside the PhantomBot install folder and try again

**Comment by Freejack01** [comment]
OK, it has a different issue now. This is from core-error folder....

[09-18-2023 @ 17:32:05.388 GMT] [handleRequest()@Helix.java:227] java.util.concurrent.TimeoutException: null
[09-18-2023 @ 17:32:05.398 GMT] [handleRequest()@Helix.java:227]
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.gmt2001.httpclient.HttpClient.request(HttpClient.java:115)
	at tv.phantombot.twitch.api.Helix.handleRequest(Helix.java:275)
	at tv.phantombot.twitch.api.Helix.handleRequest(Helix.java:224)
	at tv.phantombot.twitch.api.Helix.handleRequest(Helix.java:354)
	at tv.phantombot.twitch.api.Helix.lambda$getClipsAsync$21(Helix.java:1255)
	at tv.phantombot.twitch.api.Helix.lambda$handleQueryAsync$3(Helix.java:361)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4470)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4551)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4313)
	at tv.phantombot.cache.TwitchCache.updateClips(TwitchCache.java:229)
	at tv.phantombot.cache.TwitchCache.lambda$startup$1(TwitchCache.java:152)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[09-18-2023 @ 17:38:05.384 GMT] [handleRequest()@Helix.java:227] java.util.concurrent.TimeoutException: null
[09-18-2023 @ 17:38:05.384 GMT] [handleRequest()@Helix.java:227]
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.gmt2001.httpclient.HttpClient.request(HttpClient.java:115)
	at tv.phantombot.twitch.api.Helix.handleRequest(Helix.java:275)
	at tv.phantombot.twitch.api.Helix.handleRequest(Helix.java:224)
	at tv.phantombot.twitch.api.Helix.handleRequest(Helix.java:354)
	at tv.phantombot.twitch.api.Helix.lambda$getClipsAsync$21(Helix.java:1255)
	at tv.phantombot.twitch.api.Helix.lambda$handleQueryAsync$3(Helix.java:361)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4470)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4551)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4313)
	at tv.phantombot.cache.TwitchCache.updateClips(TwitchCache.java:229)
	at tv.phantombot.cache.TwitchCache.lambda$startup$1(TwitchCache.java:152)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[09-18-2023 @ 18:00:35.986 GMT] [handleRequest()@Helix.java:227] java.util.concurrent.TimeoutException: null
[09-18-2023 @ 18:00:35.986 GMT] [handleRequest()@Helix.java:227]
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.gmt2001.httpclient.HttpClient.request(HttpClient.java:115)
	at tv.phantombot.twitch.api.Helix.handleRequest(Helix.java:275)
	at tv.phantombot.twitch.api.Helix.handleRequest(Helix.java:224)
	at tv.phantombot.twitch.api.Helix.handleRequest(Helix.java:354)
	at tv.phantombot.twitch.api.Helix.lambda$getChannelTeamsAsync$19(Helix.java:1073)
	at tv.phantombot.twitch.api.Helix.lambda$handleQueryAsync$3(Helix.java:361)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4470)
	at reactor.core.publisher.Mono.block(Mono.java:1709)
	at com.gmt2001.TwitchAPIv5.getChannelTeams(TwitchAPIv5.java:1079)
	at tv.phantombot.cache.TwitchTeamsCache.updateCache(TwitchTeamsCache.java:91)
	at tv.phantombot.cache.TwitchTeamsCache.run(TwitchTeamsCache.java:74)
	at java.base/java.lang.Thread.run(Unknown Source)

Still same result not able to login.

**Comment by gmt2001** [comment]
When you say can't login do you mean the panel? If yes, please open your browsers console with CTRL+SHIFT+i, go to the console tab, and report what red messages you have after trying to enter the login

**Comment by Freejack01** [comment]
This is what it says.....

TypeError: a.default.detectStore(...) is undefined
